# Generated by Django 4.1.6 on 2023-02-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=12, null=True)),
                ('Region', models.CharField(blank=True, max_length=255, null=True)),
                ('City', models.CharField(blank=True, max_length=255, null=True)),
                ('Category', models.CharField(blank=True, max_length=255, null=True)),
                ('Product', models.CharField(blank=True, max_length=255, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('UnitPrice', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Food Sales',
            },
        ),
    ]
