# Generated by Django 4.1.6 on 2023-02-09 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='food_sales',
            table='Food_Sales',
        ),
    ]
