# Generated by Django 4.1.6 on 2023-02-09 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0002_alter_food_sales_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_sales',
            name='Quantity',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='food_sales',
            name='UnitPrice',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
