# Generated by Django 4.1.6 on 2023-02-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0003_alter_food_sales_quantity_alter_food_sales_unitprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_sales',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
